const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=[['overview','◈','관찰 현황'],['changes','◎','변경 기록'],['assets','▦','대상·근거'],['tasks','▤','검토 관리'],['settings','⌁','수집·AI 연결']];
let view='overview',data={results:[],changes:[],history:[]},reviews={},loadError='',aiText='',aiReady=false;try{reviews=JSON.parse(localStorage.getItem('shield-live-reviews'))||{}}catch{}
const label=s=>({'observed':'관찰 완료','http-error':'HTTP 오류','collection-error':'수집 실패'})[s]||s;
const time=s=>s?new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+' KST':'실행 전';
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3000)}
function go(v){view=routes.some(r=>r[0]===v)?v:'overview';if(location.hash!=='#'+view)location.hash=view;render()}
window.addEventListener('hashchange',()=>go(location.hash.slice(1)));
async function refresh(){try{const r=await fetch('/shield/data/latest.json',{cache:'no-store'});if(!r.ok)throw Error();data=await r.json();if(!Array.isArray(data.results)||!Array.isArray(data.changes))throw Error();loadError=''}catch{loadError='관찰 기록을 읽지 못했습니다. 이전 표시 내용은 최신 결과가 아닐 수 있습니다.'}try{const r=await fetch('/api/shield-report');if(r.ok){const s=await r.json();aiReady=s.configured}}catch{}render()}
function intro(en,title,sub){return `<div class="top"><div><span class="eyebrow">${en}</span><h1>${title}</h1><p>${sub}</p></div><div class="actions"><button onclick="refresh()">기록 새로고침</button><button onclick="exportReport()">리포트 다운로드</button></div></div><div class="demo">공개 홈페이지 관찰만 수행합니다. 고객정보·인증 후 서비스·로그인·DB·반출 이벤트는 관찰하지 않습니다. 변화나 헤더 부재만으로 해킹·유출·취약점을 확정할 수 없습니다.</div>${loadError?`<div class="demo">${esc(loadError)}</div>`:''}`}
function empty(){return `<div class="empty">${esc(data.message||'아직 수집된 결과가 없습니다.')}<br><a href="https://github.com/namonamho88-ui/scare/actions/workflows/shield-monitor.yml" target="_blank" rel="noopener">GitHub Actions 실행 현황</a></div>`}
function table(results){return results.length?`<div class="tablewrap"><table><thead><tr><th>그룹사 / 도메인</th><th>상태</th><th>HTTP</th><th>인증서 잔여일</th><th>근거</th></tr></thead><tbody>${results.map(r=>`<tr><td>${esc(r.org)}<small>${esc(new URL(r.url).hostname)}</small></td><td><span class="badge ${r.status==='observed'?'cyan':'amber'}">${label(r.status)}</span></td><td>${r.httpStatus??'—'}</td><td>${r.certificate?.daysRemaining??'—'}</td><td><button onclick="evidence('${r.id}')">상세</button></td></tr>`).join('')}</tbody></table></div>`:empty()}
function overview(){const good=data.results.filter(r=>r.status==='observed').length;return `${intro('PUBLIC OBSERVATION','외부에 드러난 변화부터 확인합니다.','마지막 수집 기록: '+time(data.generatedAt))}<div class="stats">${[['관찰 대상','4','대표 홈페이지 / 전체 자산 아님'],['관찰 완료',good,'수집 성공 / 안전 판정 아님'],['수집 실패·HTTP 오류',data.results.length-good,'점검 공백 포함'],['변경·검토 기록',data.changes.length,'정상 변경일 수 있음']].map(([a,b,c])=>`<div class="stat"><small>${a}</small><strong>${b}<b> 건</b></strong><small>${c}</small></div>`).join('')}</div><div class="grid"><div class="panel"><div class="sectionhead"><h2>공개 홈페이지 관찰</h2><small>로그인 없이 HTTPS GET</small></div>${table(data.results)}</div><div class="panel"><span class="eyebrow">COVERAGE</span><h3>개인정보 유출 감지는 미연결입니다.</h3><p class="muted">공개 페이지 상태가 정상이어도 인증·조회 권한 오류나 내부 유출이 존재할 수 있습니다.</p><div class="minirow"><span>인증·조회 이벤트</span><span class="badge amber">미연결</span></div><div class="minirow"><span>DLP·SIEM·WAF</span><span class="badge amber">미연결</span></div><div class="minirow"><span>자동 차단</span><span class="badge amber">미연결</span></div><button style="margin-top:18px" onclick="go('settings')">운영 연결 상태 보기</button></div></div><div class="panel wide"><div class="sectionhead"><h2>최근 실행 이력</h2><small>최대 30회 / 원문 미보관</small></div>${data.history.length?`<div class="tablewrap"><table><thead><tr><th>실행 시각</th><th>완료</th><th>오류</th><th>변경</th></tr></thead><tbody>${data.history.slice().reverse().map(h=>`<tr><td>${time(h.at)}</td><td>${h.observed}</td><td>${h.failed}</td><td>${h.changes}</td></tr>`).join('')}</tbody></table></div>`:empty()}</div>`}
function changeList(list){return list.length?list.map(c=>`<div class="summary"><span class="badge ${c.level==='priority'?'red':c.level==='info'?'':'amber'}">${c.level==='priority'?'우선 확인':c.level==='info'?'기준 등록':'변화 검토'}</span><h3>${esc(c.org)} · ${esc(c.summary)}</h3><small>${time(c.checkedAt)} · ${esc(c.kind)}</small><div class="actions" style="margin-top:12px"><button onclick="evidence('${c.targetId}')">관찰 근거</button><button onclick="reviewForm('${c.id}')">검토 기록</button><span class="badge">${esc(reviews[c.id]?.status||'미확인')}</span></div></div>`).join(''):empty()}
function changes(){return `${intro('CHANGE RECORD','변화를 위험으로 단정하지 않습니다.','이전의 마지막 정상 관찰과 비교합니다. 수집 실패는 기준값을 덮어쓰지 않습니다.')}<div class="panel">${changeList(data.changes)}</div>`}
function assets(){return `${intro('SCOPE & EVIDENCE','대표 홈페이지 4곳, 한정된 관찰 범위.','대상 추가는 저장소의 검토된 도메인 목록 변경으로 관리합니다. 임의 URL 점검 API는 제공하지 않습니다.')}<div class="panel">${table(data.results)}<div class="answer">예정 대상: www.shinhan.com · www.shinhancard.com · www.shinhanlife.co.kr · www.shinhansec.com<br>범위: DNS 공개 주소 확인, 인증서 만료·변경, HTTP 상태, 주요 헤더의 존재·지문, HTML 지문, 외부 스크립트 호스트.<br>전체 하위 사이트·인증 영역·포트·취약점 공격 테스트는 포함하지 않습니다.</div></div>`}
function evidence(id){const r=data.results.find(r=>r.id===id);if(!r)return;$('modalbody').innerHTML=`<span class="badge">${esc(r.org)}</span><h2>${esc(r.url)}</h2><p class="muted">${time(r.checkedAt)} · ${label(r.status)}</p><div class="evidence"><div><h3>응답 관찰</h3><p>HTTP ${r.httpStatus??'—'}<br>응답 ${r.durationMs}ms<br>리다이렉트 ${r.redirects??'—'}회<br>오류: ${esc(r.error||'없음')}</p></div><div><h3>인증서</h3><p>유효기한: ${esc(r.certificate?.validTo||'미수집')}<br>잔여: ${r.certificate?.daysRemaining??'—'}일</p><code>${esc(r.certificate?.fingerprint||'')}</code></div></div><h3>헤더 관찰</h3>${Object.entries(r.securityHeaders||{}).map(([k,v])=>`<div class="minirow"><span>${k}</span><span>${v.present?'관찰됨':'관찰 안 됨'}</span></div>`).join('')}<h3>외부 스크립트 호스트</h3><div class="answer">${esc((r.scriptOrigins||[]).join('\n')||'관찰 없음 / HTML에 직접 포함된 참조만 확인')}</div><h3>HTML 지문</h3><code style="overflow-wrap:anywhere">${esc(r.pageHash||'미수집')}</code><div class="demo">HTML 원문·쿠키·고객정보를 저장하지 않습니다. JavaScript 실행 후 동적 요청은 포함하지 않습니다. 접근 차단·403은 수집 환경에 대한 차단일 수 있습니다.</div>`;$('modal').showModal()}
function tasks(){return `${intro('REVIEW WORKSPACE','검토 근거와 처리 상태를 남깁니다.','이 브라우저에서만 저장됩니다. 공동 담당자 배정·실제 보안 조치와는 연동되지 않습니다.')}<div class="panel">${changeList(data.changes)}</div>`}
function reviewForm(id){const c=data.changes.find(x=>x.id===id);if(!c)return;const r=reviews[id]||{};$('modalbody').innerHTML=`<h2>${esc(c.org)} · 변경 검토</h2><p>${esc(c.summary)}</p><form onsubmit="event.preventDefault();saveReview('${id}')"><label>검토 상태<select id="reviewstatus" style="display:block;margin:12px 0">${['미확인','확인 중','조치 필요','정상 변경','해결'].map(x=>`<option ${x===r.status?'selected':''}>${x}</option>`).join('')}</select></label><label>공개 근거 기반 메모<textarea id="reviewnote" maxlength="1000">${esc(r.note||'')}</textarea></label><p><small>고객정보·내부 보안 이벤트·비밀정보는 입력하지 마세요. 메모는 외부 AI로 전송하지 않습니다.</small></p><button class="primary">검토 저장</button></form>`;$('modal').showModal()}
function saveReview(id){const s=$('reviewstatus').value,n=$('reviewnote').value.trim();if(['정상 변경','해결'].includes(s)&&!n)return toast('종결 근거를 메모해주세요.');reviews[id]={status:s,note:n};try{localStorage.setItem('shield-live-reviews',JSON.stringify(reviews))}catch{return toast('브라우저 저장 실패')} $('modal').close();render();toast('현재 브라우저에 저장했습니다.')}
function settings(){return `${intro('COLLECTION & AI','관찰 수집과 AI 설명을 분리합니다.','자동 수집은 GitHub Actions, AI 설명은 서버의 OpenAI API에서 처리합니다.')}<div class="grid"><div class="panel"><h2>매일 08:00 KST 수집</h2><p class="muted">GitHub Actions 스케줄은 지연될 수 있습니다. 워크플로 활성화·실행 성공은 GitHub에서 확인하세요.</p><a href="https://github.com/namonamho88-ui/scare/actions/workflows/shield-monitor.yml" target="_blank" rel="noopener">실행·실패 이력 확인</a><div class="minirow"><span>마지막 수집</span><span>${time(data.generatedAt)}</span></div><div class="minirow"><span>AI 서버 설정</span><span class="badge ${aiReady?'cyan':'amber'}">${aiReady?'설정됨 / 실제 연결 미검증':'미설정'}</span></div><div class="answer">Vercel 서버 설정<br>OPENAI_API_KEY: 실제 비밀 키<br>OPENAI_MODEL: 사용 가능한 모델 ID<br>SHIELD_ACCESS_TOKEN: 별도 운영자 토큰(24자 이상)<br><br>‘My Test Key’는 표시 이름이며 인증에 사용하는 비밀 키 값이 아닙니다.</div></div><div class="panel"><h2>AI 관찰 브리프</h2><p class="muted">서버에 저장된 공개 관찰 통계만 전달합니다. 메모·고객정보·HTML 원문을 보내지 않습니다.</p><form onsubmit="event.preventDefault();generateBrief()"><label style="font-size:14px">운영자 토큰 (OpenAI 키를 입력하지 마세요)<input type="password" id="operatortoken" autocomplete="off" style="width:100%;margin:12px 0" required></label><button class="primary" id="aibutton" type="submit">AI 설명 생성</button></form><small>토큰은 저장하지 않습니다. 이 기능은 API 이용료가 발생할 수 있습니다.</small><div id="airesult" class="answer">${esc(aiText||'아직 생성된 설명이 없습니다.')}</div></div></div>`}
async function generateBrief(){const token=$('operatortoken').value;if(token.startsWith('sk-'))return toast('OpenAI 키는 이 입력란에 넣지 마세요.');$('aibutton').disabled=true;try{const r=await fetch('/api/shield-report',{method:'POST',headers:{Authorization:'Bearer '+token}}),d=await r.json();if(!r.ok)throw Error(({OPERATOR_TOKEN_REQUIRED:'운영자 토큰을 확인해주세요.',OPENAI_NOT_CONFIGURED:'서버 OpenAI 설정이 없습니다.',NO_OBSERVATIONS:'수집 결과가 없습니다.'})[d.error]||'AI 생성 실패: 서버 설정·모델·한도를 확인해주세요.');aiText=d.text;$('airesult').textContent=aiText}catch(e){toast(e.message)}finally{$('aibutton').disabled=false;$('operatortoken').value=''}}
function exportReport(){const text=`SHINHAN SHIELD 공개 웹 관찰\n관찰일: ${time(data.generatedAt)}\n침해·유출·안전 여부를 판정하지 않습니다.\n\n${data.results.map(r=>`${r.org} / ${r.url}\n${label(r.status)} / HTTP ${r.httpStatus??'미수집'} / ${time(r.checkedAt)}`).join('\n\n')}\n\n변경\n${data.changes.map(c=>c.org+': '+c.summary).join('\n')}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));a.download='shield-public-observation.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function render(){$('nav').innerHTML=routes.map(([v,i,n])=>`<button class="${v===view?'active':''}" onclick="go('${v}')"><span>${i}</span>${n}</button>`).join('');$('crumb').textContent=routes.find(r=>r[0]===view)[2];$('freshness').textContent=loadError?'기록 읽기 실패':!data.generatedAt?'첫 실행 전':Date.now()-Date.parse(data.generatedAt)>36*3600000?'기록 지연 / 최신성 확인':'수집 기록 있음';$('main').innerHTML=({overview,changes,assets,tasks,settings}[view])()}
go(location.hash.slice(1));refresh();
